---
title: "P8105_hw2_qw2282"
author: "Qinyao Wu"
date: "9/28/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(p8105.datasets)
```

```{r}
#Import the data
nyc_transit_data = read.csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
  janitor::clean_names() %>% 
  select(line, station_name, station_latitude, station_longitude, starts_with("route"), entry, vending, entrance_type, starts_with("ada")) %>% 
  mutate(entry = recode(entry, `YES` = TRUE, `NO` = FALSE)) 


distinct_station = distinct(nyc_transit_data, station_name,route1, .keep_all = TRUE)
dim(distinct_station)  #451 distinct stations.

ada_com_distinction_station = filter(distinct_station, ada == TRUE)
dim(ada_com_distinction_station) #76 are ada complimented. 

without_vending = filter(distinct_station, vending == "NO")
without_vending_allow_entry = 
  filter(distinct_station, vending == "NO", entry == TRUE)
proportion = nrow(without_vending_allow_entry) / nrow(without_vending) #55.6%

transitdata_tidy = gather(nyc_transit_data, key = route_number, value = route_name, route1:route11)

station_A_route = 
  filter(transitdata_tidy, route_name == "A") %>% 
  distinct(station_name, .keep_all = TRUE)  %>% #56 distinct stations serve A
  filter(ada == TRUE) #15 of them have ada.

```


##Problem 2
```{r problem 2}

trash_wheel_data = readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = 1, range = "A2:N258") %>% 
  janitor::clean_names() 

trash_wheel_data = filter(trash_wheel_data, !is.na(dumpster)) %>% 
  mutate(sports_balls = as.integer(round(sports_balls, 0)))

precipitation_2016 = readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = 4, range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(month)) %>% 
  mutate(year = 2016)
  
precipitation_2017 = readxl::read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = 3, range = "A2:B15") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(month)) %>% 
  mutate(year = 2017)

precipitation_tidy = bind_rows(precipitation_2016, precipitation_2017) %>%
  janitor::clean_names() %>% 
  mutate(month = month.name[month])
  



```


##Problem 3
```{r}
library(p8105.datasets)
data(brfss_smart2010)


brfss_smart2010 = janitor::clean_names(brfss_smart2010) %>% 
  filter(topic == "Overall Health") %>% 
  select(-c(topic, class, question, sample_size, confidence_limit_low:geo_location)) %>% 
  spread( key = response, value = data_value)

#Unique locations
distinct_location = distinct(brfss_smart2010, locationdesc, .keep_all = TRUE) #total of 404 different locations

distinct_state = distinct(brfss_smart2010, locationabbr, .keep_all = TRUE) #51 states. 

tail(names(sort(table(brfss_smart2010$locationabbr))), 1) #NJ is the most frequently appeared states.

ggplot(filter(brfss_smart2010, year == 2002), aes(x = Excellent)) + geom_histogram()


ggplot(filter(brfss_smart2010, locationdesc == "NY - New York County" | locationdesc == "NY - Queens County"), aes(x = year, y = Excellent)) + geom_point(aes(color = locationdesc), alpha = .5)
  

```






